Shreyansh | Week5 - Implementation of Counter using Redux
choudhary-keshav/javascript-training pull request #13
Opened 2024-03-22 12:12 UTC by shreyansh-khatri

Pull Request Questionnaire

1) Briefly describe your change.
 Implemented Counter using redux and integrated it with main assignment.

2) What parts of the application are affected by your change?
My changes only affected the week5-Shreyansh branch and the components inside it.

3) How did you test your change?
I tested various parts such as validation, different inputs and some other edge cases.

2024-03-25 06:42 UTC, aditya-s-19 commented on src/App.tsx
> +            <Route path='week5/*' element={<ShreyanshWeek5 />}></Route>
use self closing tag

2024-03-25 06:42 UTC, aditya-s-19 commented on src/components/Home/Shreyansh/Week5/Counter/CounterStyle.ts
> +    margin-top: 50px;
use a single margin for both these styles

2024-03-26 03:21 UTC, choudhary-keshav requested changes

2024-03-26 03:21 UTC, choudhary-keshav commented on src/components/Home/Shreyansh/Week5/Counter/Counter.tsx
> +        <div className='mainContainer'>
There is no need of extra div, line 12 & 13 can be of a single line

2024-03-26 09:00 UTC, RitikaGarg-ITT commented on src/components/Home/Shreyansh/index.tsx
>      </ShreyanshWrapper>
It is been asked to remove this name from the css file.Dont use person's name in main component file

2024-03-26 11:54 UTC, choudhary-keshav submitted a review, later dismissed

2024-03-26 11:55 UTC, RitikaGarg-ITT approved these changes, later dismissed

2024-03-26 11:56 UTC, aditya-s-19 approved these changes, later dismissed

2024-03-27 13:12 UTC, shreegovinda submitted a review, later dismissed

2024-04-01 06:47 UTC, choudhary-keshav approved these changes

2024-04-01 06:48 UTC, aditya-s-19 approved these changes

2024-04-01 06:48 UTC, merged