initial commit
choudhary-keshav/javascript-training pull request #5
Opened 2024-03-18 11:54 UTC by shreyansh-khatri

1) Briefly describe your change.
 Uploaded week4 assignment of ReactJS and also integrated it in the common project for all trainees.
 
 2) What parts of the application are affected by your change?
 My changes only affected the week4-Shreyansh branch and the components inside it.
 
 3) How did you test your change?
 I tested various parts such as validation, different inputs and some other edge cases.

2024-03-19 06:08 UTC, shreegovinda commented on interns-react-weekly-assignments/src/components/Home/Shreyansh/Week_4/components/Feature3/Feature3Style.ts
> +    box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
use single common way of styling colors

2024-03-19 06:08 UTC, shreegovinda commented on interns-react-weekly-assignments/src/components/Home/Shreyansh/index.tsx
> +  const [selectedWeek, setSelectedWeek] = useState('');
type

2024-03-20 04:38 UTC, Harrrrry requested changes

2024-03-20 04:38 UTC, Harrrrry commented on interns-react-weekly-assignments/src/components/Home/Shreyansh/Week_4/DashboardStyle.ts
> +    background-color: gray;
use hexacode

2024-03-20 04:38 UTC, Harrrrry commented on interns-react-weekly-assignments/src/components/Home/Shreyansh/Week_4/components/Feature2/Feature2.tsx
> +import { Feature2Wrapper } from "./Feature2Style";
I recommend to have proper name of file and folder.
instead of feature2, it should be calculator

2024-03-20 04:38 UTC, Harrrrry commented on interns-react-weekly-assignments/src/components/Home/Shreyansh/Week_4/components/Feature3/Feature3.tsx
> +            <option value="USD">USD</option>
Use labels for string

2024-03-20 04:38 UTC, Harrrrry commented on interns-react-weekly-assignments/src/components/Home/Shreyansh/Week_4/components/Feature3/Feature3.tsx
> +          <select value={targetCurrency} onChange={handleTargetCurrencyChange}>
This select is duplicate code, It should be common with params as per the functionality

2024-03-20 04:38 UTC, Harrrrry commented on interns-react-weekly-assignments/src/components/Home/Shreyansh/index.tsx
>      <ShreyanshWrapper>
Use proper name

2024-03-20 04:38 UTC, Harrrrry commented on interns-react-weekly-assignments/src/components/Home/Shreyansh/styles.ts
> +       .weekButtonsContainer {
Do proper indentation

2024-03-20 05:59 UTC, anusreesubash commented on interns-react-weekly-assignments/src/App.tsx
> +import Week_4 from './components/Home/Shreyansh/Week_4'
can you follow the same naming format that is being used, to diffrenetiate maybe you can add your name as prefix while importing let us not have _ while naming component

2024-03-20 05:59 UTC, anusreesubash commented on interns-react-weekly-assignments/src/components/Home/Shreyansh/Week_4/Dashboard.tsx
> +            <ul className="feature-button">
can you use a map for this instead of having multiple li elements also please add key for each li elements

2024-03-20 05:59 UTC, anusreesubash commented on interns-react-weekly-assignments/src/components/Home/Shreyansh/Week_4/index.tsx
> +  <Dashboard/>
is this file formatted?

2024-03-20 06:58 UTC, RitikaGarg-ITT commented on src/components/Home/Shreyansh/Week_4/components/Feature1/Feature1Style.ts
> +  .funFactContainer {
you are using different naming convention in one file you are using hyphen naming in other file you are using camelCasing

2024-03-20 07:46 UTC, shreegovinda commented on src/components/Home/Shreyansh/index.tsx
> +  const [selectedWeek, setSelectedWeek] = useState('');
type

2024-03-20 07:46 UTC, shreegovinda commented on src/components/Home/Keshav/Week1/index.tsx
> +const Week1 = () => {
why type is removed?

2024-03-20 07:46 UTC, shreegovinda commented on src/components/Home/Shreyansh/Week_4/components/Feature1/Feature1.tsx
> +  const fetchRandomFact = async () => {
type

2024-03-20 08:38 UTC, aditya-s-19 commented on src/components/Home/Shreyansh/Week_4/Dashboard.tsx
> +                <button>Feature 5</button>
See if these can be reduced with map()

2024-03-20 08:40 UTC, aditya-s-19 commented on src/components/Home/Shreyansh/Week_4/DashboardStyle.ts
> +    background-color: gray;
both direct colors and hex values in code

2024-03-20 08:49 UTC, aditya-s-19 commented on src/components/Home/Shreyansh/Week_4/components/Feature3/Feature3.tsx
> +            <option value='INR'>INR</option>
again, do it with map()

2024-03-20 08:49 UTC, aditya-s-19 commented on src/components/Home/Shreyansh/Week_4/components/Feature3/Feature3.tsx
> +  const handleAmountChange = (e: React.ChangeEvent<HTMLInputElement>) => {
specify return types in functions as well

2024-03-20 12:12 UTC, shreegovinda submitted a review, later dismissed

2024-03-20 12:12 UTC, choudhary-keshav approved these changes, later dismissed

2024-03-21 03:46 UTC, Harrrrry approved these changes, later dismissed

2024-03-21 03:56 UTC, aditya-s-19 approved these changes, later dismissed

2024-03-21 04:06 UTC, Harrrrry approved these changes

2024-03-21 04:08 UTC, aditya-s-19 approved these changes

2024-03-21 04:19 UTC, shreegovinda approved these changes

2024-03-21 04:20 UTC, merged